redding/ardb

lib/ardb/record_spy.rb
lib/ardb/relation_spy.rb
test/helper.rb
test/support/factory.rb
test/unit/record_spy_tests.rb
test/unit/relation_spy_tests.rb

This updates the `RecordSpy` to have scope methods and to use
the `RelationSpy` to spy them. This is a common pattern that has
proven to be useful for unit testing scopes when a test DB is not
available. This makes the pattern part of the `RecordSpy` so it
doesn't have to be redone everytime we need to unit test a scope.
This also updates `RelationSpy` to have a `reset!` method. This
is useful because a `RecordSpy`s relation spy will continue to
build up expressions on it. This can be annoying because the
record spy class is typically a global and tests can easily
interfere with one another. This provides a method to reset the
relation spy to avoid these issues.
@kellyredding - Ready for review. This is the first of 2 updates I want to make to `RecordSpy`.

Add scope methods to `RecordSpy`, use `RelationSpy`

---

ardb.gemspec
lib/ardb/runner/migrate_command.rb

This is just a minor cleanup.  I ran into a cryptic migration error
and had no context.  I updated this and reran my migration and the
backtrace confirmed it was coming from activerecord.  This helped
tip me off to a typo in my migration.
Now, I'd prefer activerecord throw a less cryptic error, but that
is a separate issue.  This at least helped me figure things out.

migrate cli: show any error backtraces

---

Gemfile
ardb.gemspec
lib/ardb/adapter/postgresql.rb
test/unit/adapter/postgresql_tests.rb

This updates to use the new scmd which changes how it takes an
env hash. This updates the scmd calls to use the new interface.
No functionality was changed, just update the existing logic to
work with the change to scmds interface.

Update to use the new scmd

---

lib/ardb/relation_spy.rb
lib/ardb/use_db_default.rb
test/unit/relation_spy_tests.rb
test/unit/use_db_default_tests.rb

This adds a use db default mixin which will allow columns to be
defaulted by the db. This is specifically needed to make use of
defaulting a non primary key column using a postgres sequence.
Firstly, activerecord doesn't really use defaults that are
configured on columns. For simple defaults, like a literal value,
activerecord does the actual defaulting when you instantiate an
instance of a record. Otherwise all columns have a `nil` value.
When these are saved, activerecord sends values for all columns
which keeps the DB from defaulting them.
This allows the DB to default values by keeping activerecord from
sending them when it runs a sql `INSERT`. To do this, the mixin
adds an around create callback that will check if a column has
been changed. If it hasn't then we remove it from the the …

Add `Ardb::UseDbDefault` mixin

---

lib/ardb/has_slug.rb
lib/ardb/use_db_default.rb
test/unit/has_slug_tests.rb
test/unit/use_db_default_tests.rb

This adds a `HasSlug` mixin that provides automatic slugging to
active record models. This allows creating readable slugs for
easily.
The mixin adds a `has_slug` class method when included. This can
be used to add the automatic slugging behavior and configure it as
needed. The `has_slug` requires a source proc for configuring
how the slug is generated. It uses this to generate the initial
slug.
Once `has_slug` has been called, it adds validations and callbacks.
It adds a validates presence on update for the configured slug
attribute. Its on update because slugs are generated after the
model has been saved (so the `id` can be used). It also adds a
validates uniqueness of for the slug attribute. This can be
further customized by specifying a unique scope option when
calling `has_slug`. It …

Add `HasSlug` mixin

---

lib/ardb/has_slug.rb
test/unit/has_slug_tests.rb

This fixes a bug with `HasSlug` that caused it to not set its slug
when the source was already a valid slug. This was missed when
initially adding the `HasSlug` mixin.
The tests always assumed slugging the source produced something
different than the source's original value. The problem was that
the source value was being used to see if it matched the generated
slug instead of the slugs attributes current value. In the tests,
the source is setup so it will never match the generated slug
because we are testing other behavior like using the preprocessor
and allowing underscores. This adds a test that makes the source
and the generated slug match but the slug attribute be different
and ensures it sets the slug correctly.
This also fixes a minor bug with the slug tests using non-word
chars. I …

Fix has slug when the source is already a valid slug

---

lib/ardb/adapter/base.rb
lib/ardb/adapter_spy.rb
lib/ardb/runner/migrate_command.rb
lib/ardb/test_helpers.rb
test/unit/adapter/base_tests.rb
test/unit/runner/migrate_command_tests.rb
test/unit/test_helpers_tests.rb

This moves the logic for migrating a DB into Adapter::Base so that
it may be called independently of the command line.  Though the migration
doesn't directly use the Adapter, it is a common place for it to live
so that all Adapters can migrate the db in a similar manner as they
create or drop the db.
This also updates the TestHelpers so that apps do not need to directly
interact with the Adapter to drop, create, migrate, or reset the db.
This used the existing pattern of only running a DB command once per
call, but still allowing users to force the call using the bang version
of the method.

Move the logic for Migrating a DB into Adapter::Base

---

lib/ardb/adapter_spy.rb
lib/ardb/runner/create_command.rb
lib/ardb/runner/drop_command.rb
lib/ardb/runner/migrate_command.rb
test/unit/adapter_spy_tests.rb
test/unit/runner/connect_command_tests.rb
test/unit/runner/create_command_tests.rb
test/unit/runner/drop_command_tests.rb
test/unit/runner/migrate_command_tests.rb

This updates the testing of Ardb Commands that use the Adapter to
use the Ardb::AdapterSpy.  This allows the testing of `run` behavior.
This also updates those commands to optionally accept an output and
error IO, and use those IO's rather than `$stdout` and `$stderr`.  This
was done so that in the test environment we can avoid writing to the
console when running these Commands.
This also updates the AdapterSpy to include methods for spying the
`dump_schema` command as well as helpers to determine if a command
was run.

Update Adapter based Commands to use AdapterSpy in testing

---

ardb.gemspec
lib/ardb/default_order_by.rb
lib/ardb/relation_spy.rb
test/unit/default_order_by_tests.rb

This adds a default order by mixin that provides the logic for
automatically defaulting a record to the next available "order-by"
value. This is intended to make it simple to easy order a set of
records when they are initially created.
The mixin adds a before validation callback that will run a query
to check for the current max order by value in the DB. It will then
set its order by value to the current max + 1. This makes records
order by default in the order they are created.
The mixin also allows providing a custom scope proc. This will be
used when determining the current max order by value. This can be
used to group or scope order by values. For example, if all the
records have a grouping and each grouping of records should be
ordered separately then the scope can be used to scope …

Add `DefaultOrderBy` mixin

---

lib/ardb/adapter_spy.rb
lib/ardb/has_slug.rb
lib/ardb/record_spy.rb
lib/ardb/use_db_default.rb
test/unit/adapter_spy_tests.rb
test/unit/default_order_by_tests.rb
test/unit/has_slug_tests.rb
test/unit/record_spy_tests.rb
test/unit/use_db_default_tests.rb

This updates the other mixins to use `MuchPlugin` now that its
being brought in. This provides protection from included logic
getting run multiple times. This doesn't change any functionality
of how the mixins work.

Use `MuchPlugin` in other mixins

---

lib/ardb/runner/migrate_command.rb
test/unit/runner/migrate_command_tests.rb

This updates the migrate command to not always dump the schema. If
the no schema env var is set then it won't dump the schema after it
migrates. This is convenient when deploying migrations and using
a sql schema. The bins needed to dump the SQL schema may not be
available on the machine running the migration. Also, the schema
should have been dumped when the migration was run locally. It
doesn't need to be dumped again by the server.

Allow not dumping schema when migrating db

---

lib/ardb/adapter/base.rb
lib/ardb/adapter_spy.rb
lib/ardb/runner/connect_command.rb
lib/ardb/test_helpers.rb
test/unit/adapter/base_tests.rb
test/unit/adapter_spy_tests.rb
test/unit/runner/connect_command_tests.rb
test/unit/runner/create_command_tests.rb
test/unit/runner/drop_command_tests.rb
test/unit/runner/migrate_command_tests.rb
test/unit/test_helpers_tests.rb

This centralizes all command behavior and makes it accessible in
a non CLI manner via the adapter.  This keeps the connect logic
consistent with the migrate/etc logic.
To support this, the adapter spy now have "connect db" methods and
the test helpers now have "connect db methods.
This also includes some test cleanups and makes the connect command
tests more robust.  They now closely match the migrate command tests.

move connect command core logic into a `connect_db` adapter method

---

bin/ardb
lib/ardb/cli.rb
lib/ardb/clirb.rb
test/unit/cli_tests.rb

This reworks the CLI to handle each sub command using its own CLIRB
config/parser.  This allows the main CLI to have its own options and
help message and each sub command to also have their own options and
help message.
Note: this is part of a large effort to rework the CLI implementation.
Overall, no external behavior changes will happen but the CLI will
be easier to maintain and extend.  Right now this just sets up the
framework so we can move each sub command into it.  After we move
all the sub commands, the runner will just go away.
Note also: there were no CLI specific tests before so this adds some.
@jcredding ready for review.  Note that this is against a feature branch.  I'll probably do each sub command in its own PR and then do a cleanup commit where I remove the runner at the …

rework CLI sub command handling and framework

---

lib/ardb/cli.rb
test/unit/cli_tests.rb

This method is a bit superfluous and can be incorporated into the
run method. The goal is to not have to remember to call both init
and run just the actually run cli commands.
This removes the method and updates the tests appropriately. This
is part of setting up our sub-command framework.

rework cli sub-commands to not have an `init` method

---

lib/ardb.rb
lib/ardb/cli.rb
test/unit/cli_tests.rb

This makes the CLI in general init Ardb without establishing a
connection regardless of the command - all commands should expect
Ardb to be configured and initialized.
This also updates the sub-commands to not treat clirb parse errors
as command errors.  This breaks the built in clirb error handling
the CLI does.
These were things that were discovered while using the new CLI in
an application.

rework how CLI initializes Ardb and handles clirb exceptions

---

ardb.gemspec
lib/ardb/adapter_spy.rb
lib/ardb/default_order_by.rb
lib/ardb/has_slug.rb
lib/ardb/record_spy.rb
lib/ardb/relation_spy.rb
lib/ardb/use_db_default.rb
test/unit/adapter_spy_tests.rb
test/unit/default_order_by_tests.rb
test/unit/has_slug_tests.rb
test/unit/record_spy_tests.rb
test/unit/use_db_default_tests.rb

This adds a default order by mixin and switches to using much-plugin in all of Ardb's mixins.
@kellyredding - FYI.

Feature: Add `DefaultOrderBy` and use `MuchPlugin

---

lib/ardb.rb
lib/ardb/require_autoloaded_active_record_files.rb
script/determine_autoloaded_active_record_files.rb

This adds requiring all of activerecord to ardb's init. This avoids
uninitialized constant errors that happen in threaded environments.
Activerecord uses ruby's autoload which isn't threadsafe. This
is intended to avoid autoload by manually requiring all the files
needed. `Ardb.init` should be run when an app is initialized before
any threads are created.
This also adds a script for determining the files that need to be
manually required. This is a tool to use when activerecord is
updated to ensure we are continue requiring any new files that get
added (or stop requiring old files that are removed).

Add requiring all of activerecord to init

---

lib/ardb.rb
test/unit/config_tests.rb

This exposes a `pool` and `checkout_timeout` option for the ardb
db config. This allows changing activerecord's pool size and the
timeout it uses for checking out a new connection from the pool.
These typically aren't set unless the process is using multiple
threads. This allows more control over the activerecord
configuration in a threaded environment. This also makes it
possible to set all of the common activerecord connection options
using ardb.

Add `pool` and `checkout_timeout` options to ardb db config

---

lib/ardb/db_tests.rb
test/unit/db_tests_tests.rb

This adds a `DbTests` assert context which can be used to run
tests in a transaction that is rolled back. This is being added
to help with tests that need to interact with a DB. The DB is a
global state for a test suite and this handles automatically
resetting it. This makes it so tests don't have to handle cleaning
up data they created or deal with a dirty global state. Finally,
this also can improve test speed by never committing anything to
the DB.
The `DbTests` relies on the assert testing library but assert is
not being brought in as a formal dependency. The `DbTests` is an
optional helper that doesn't have to be used. Thus, the user of
ardb is required to bring in ardb if they want to use `DbTests`.
If there are ever more test helpers (for assert or other testing
libraries) then we …

Add `DbTests` assert context

---

lib/ardb.rb
lib/ardb/adapter/base.rb
test/unit/adapter/base_tests.rb
test/unit/ardb_tests.rb

This adds an `escape_like_pattern` helper method to adapters. This
can be used to escape wildcard characters in `LIKE` patterns so
users don't accidentally use wildcards. A typical use-case is
using a user supplied string to run a SQL query using `LIKE`. The
user may use characters like `%` and `_` which have special
meaning unless they are properly escaped. This helper can be used
to escape the user input so if a wildcard was used it is treated
literally. The helper also escapes the escape char which ensures
it is also treated literally. More than likely, a user intends the
characters to be treated literally and not have their special
meaning.
This is being added as an adapter helper method because its
possible that each adapter may have custom escape logic for like
patterns. The current …

Add `escape_like_pattern` helper method to adapters

---

lib/ardb/has_slug.rb
test/unit/has_slug_tests.rb

This allows you to use the slugging behavior to set values but
not force those values to be unique.  This is more edge-case behavior
on a slug so we still validate uniqueness by default.  However, this
allows you to use slugging logic less-normalized data.

has slug: add option for skipping the uniqueness validation

---

lib/ardb.rb
test/helper.rb
test/support/relative_require_test_db_file.rb
test/support/require_test_db_file.rb
test/unit/ardb_tests.rb
test/unit/config_tests.rb

This removes the `db_file` as a config option and adds the ability
to require it relative to the current working directory. This is
part of an effort to remove ns-options from the config and is also
part of updating Ardb to work with ruby 1.9+.
First, this removes the `db_file` as a config option and switches
to always using the env var. This is part of removing ns-options
because this reduces coupling to the `Config` and is one less
config option that has to be ported to a non ns-options
implementation. The `db_file` was confusing as a config option
because practically the `db_file` always needed to be configured
outside of the actual db file to be of any use. The design of
Ardb is that all the common configuration can be contained in the
db file except the db file configuration itself. …

Remove `db_file` as a config option

---

ardb.gemspec
lib/ardb.rb
lib/ardb/adapter/base.rb
lib/ardb/adapter/postgresql.rb
lib/ardb/adapter/sqlite.rb
lib/ardb/cli.rb
lib/ardb/migration_helpers.rb
test/unit/adapter/base_tests.rb
test/unit/adapter/postgresql_tests.rb
test/unit/adapter/sqlite_tests.rb
test/unit/ardb_tests.rb
test/unit/cli_tests.rb
test/unit/config_tests.rb
test/unit/migration_helpers_tests.rb
tmp/testdb/config/db.rb

This removes ns-options from the `Config` class and simplifies the
`Config`. This is being done for a number of reasons. Ardb config
doesn't need to leverage all of the functionality of ns-options so
its overkill to use it for its config. This also simplifies the
upgrade path to a newer ruby because ns-options is not currently
compatible with it. Also by removing a dependency this decouples
and makes the maintenance of ardb easier.
This changes the `Config` class to no longer include ns-options
and changes its options to simple attribute reader/writers and
no longer be accessed via a `db` namespace. The activerecord
attrs are simple accessors and no special processing or type
casting is done. This allows users to have essentially direct
access to the activerecord options. This lets them …

Remove ns-options from `Config`

---

lib/ardb/adapter_spy.rb
test/unit/adapter_spy_tests.rb
test/unit/cli_tests.rb
test/unit/migration_helpers_tests.rb
test/unit/test_helpers_tests.rb

This simplifies and expands the `AdapterSpy`. This was noticed
while working on decoupling adapters from the global `Ardb.config`.
This simplifies the `AdapterSpy` to just be an adapter (inherit
from the base adapter) that overwrites the adapter methods to be
spy methods. This also expands it to have fake foreign key sql
methods which allows using it in the migration helpers tests.
The `AdapterSpy` now inherits from `Adapters::Base`, ensuring it
has the same interface as a real adapter. It still overwrites the
adapter methods to spy on them as it did before. This removes it
as a module and dynamic class generator. In hindsight, these didn't
make sense as features. None of the tests used its ability to
add a dynamic interface to an adapter class. Furthermore, it
doesn't make good sense for …

Simplify and expand `AdapterSpy`, use in migration helpers tests

---

Gemfile
ardb.gemspec
lib/ardb/pg_json.rb
test/helper.rb
test/support/postgresql/pg_json_migrations/20160519133432_create_pg_json_migrate_test.rb
test/support/postgresql/schema.rb
test/support/postgresql/setup_test_db.rb
test/system/pg_json_tests.rb
test/unit/adapter/base_tests.rb
test/unit/ardb_tests.rb
test/unit/pg_json_tests.rb

This adds a helper file `ardb/pg_json` that can be required to
modify activerecord so that it will support postgres json columns.
This is needed for activerecord 3.2 because it doesn't support
json columns by default. This isn't required by default and should
only be used when using ardb with a postgres adapter.
This also sets up having adapter specific system tests. These were
needed to properly test the shim and make sure it modified
activerecord as expected. This only sets up postgres system tests
but this could be expanded to the other adapters and used to test
their methods. The pg json migrations are separated from regular
migrations because pg json logic is explicitly tested and there
isn't any reason for the pg json or (if there were any) postgres
system tests to have to run each …

Add shim that adds support for postgres json columns to activerecord

---

test/helper.rb
test/system/pg_json_tests.rb
test/unit/ardb_tests.rb
test/unit/cli_tests.rb
test/unit/has_slug_tests.rb
test/unit/migration_tests.rb
test/unit/record_spy_tests.rb
test/unit/use_db_default_tests.rb

This switches to using `sample` instead of `choice` but backfills
`sample` so it works in ruby 1.8.7. This is part of making sure the
gem works for newer versions of ruby. This allows the test suite to
be run on newer versions of ruby which can be used to tell if the
gem is compatible with the version or not.

Switch to using `sample` instead of `choice`, backfill for 1.8.7

---

lib/ardb.rb
lib/ardb/adapter/base.rb
lib/ardb/cli.rb
test/unit/adapter/base_tests.rb
test/unit/ardb_tests.rb
test/unit/cli_tests.rb

This changes the cli commands to not init ardb as part of the main
cli and instead wait and let the commands init it themselves. This
makes it so the cli will not error about being unable to load an
ardb db file when using `--help` or `--version`. The cli will still
error if an actual command is used that then initialized ardb.
This also has other benefits of letting the commands customize how
they want to init ardb (establish a connection or not). The
connect, drop and migrate commands all want to establish a
connection because they can assume the db should already exist. The
create command doesn't want to establish a connection ecause it
assumes the db doesn't already exist. Similarly, the generate
migration command doesn't need to establish a connection to a db
to generate a migration …

Don't init ardb until a command is run

---

lib/ardb/cli.rb
lib/ardb/cli/clirb.rb
lib/ardb/cli/commands.rb
test/unit/cli_tests.rb

This reworks the CLI and commands to follow ggem's pattern for
having a CLI with sub commands. This expands the CLI `--help`
to list all the commands with a summary message explaining them.
This is friendlier and makes it easy to see what commands are
available using the CLI.
The commands now inherit from a `ValidCommand` and are used in
conjunction with a `CommandSet` by the CLI. The `ValidCommand`
commonizes the basics of building and running a command which
avoids having to repeat the logic in each command and keep them
consistent. The `CommandSet` is built by the CLI instead of a hash
and handles mapping a command bash arg with the command class.
This allows the CLI to print out a list of all the commands and
their summary which explains what they do.
In addition to this, the args are …

Rework CLI and commands to follow ggem's pattern

---

lib/ardb/cli/commands.rb
lib/ardb/migration.rb
test/unit/cli_tests.rb
test/unit/migration_tests.rb

This switches to passing a `Config` to the `Migration` class
isntead of it referencing the global `Ardb.config`. This is to
decouple it and make it so its tests don't require ardb to be
configured and init. This doesn't change the migration class's
functionality.
This also updates the cli generate migration command to use
`Ardb.config` when it builds a `Migration`. This keeps the cli
working as it previously did.

Pass `Config` to `Migration` instead of using `Ardb.config`

---

ardb.gemspec
lib/ardb/cli/commands.rb
test/unit/cli_tests.rb

This allows individual commands to take individual options.  There
is no immediate need for this behavior but it was added to GGem (see
GGem's PR 35).  Ardb's command handling is modeled after GGem so this
is added to keep things consistent.
Note: this also updates to the latest Assert patch.  This is just
to keep up with the latest stuff.
See https://github.com/redding/ggem/pull/35 for reference.

cli: update valid commands to allow custom CLIRB build procs

---

lib/ardb.rb
lib/ardb/cli/commands.rb
test/unit/ardb_tests.rb
test/unit/cli_tests.rb

This updates ardb to throw a nice error when it can't require the
db file specified by the `ARDB_DB_FILE` env var. This is to help
users out when using hte CLI or ardb in their code.
This also updates the cli commands to specially handle this error
by moving `Ardb.init` out of their begin rescue blocks. This makes
it so the error doesn't get caught by the commands custom error
handling. Each command does custom error handling to better explain
that the action they were trying to perform couldn't be done. The
invalid db file error would be stomped by this error handling so
users wouldn't get the nice error message. By moving it out, the
inavlid db file error is handled by the CLI which displays it to
the user. Any errors thrown by `Ardb.init` should be handled this
way because they aren't …

Add nice error when ardb can't require a db file on init

---

lib/ardb/adapter/base.rb
test/unit/adapter/base_tests.rb

This updates the `escape_like_pattern` method on the adapters to
always ensure it returns the pattern that was being escaped. The
`gsub!` method will only return the string if it matched, otherwise
it returns `nil`. This caused tools using `escape_like_pattern` to
not work if nothing needed to be escaped. This was missed because
the tests only tested how it behaved with a string that the gsubs
matched.

Update `escape_like_pattern` to always return the pattern string

---

lib/ardb.rb
test/support/postgresql/setup_test_db.rb
test/unit/ardb_tests.rb

This updates ardb to raise a not initialized error when its adapter
is used before it has been `init`. This is to avoid no method
errors happening because the `adapter` is `nil`. Instead this
throws a nice error that explains ardb hasn't been init yet.
This also adds `reset_adapter` method which allows setting the
adapter back to `nil`. This was needed to reliably test that it
would throw the not initialized error. Ardb has system tests that
init ardb so its adapter can be set depending on the order the
tests are run. This updates the tests to reset the adapter to
help ensure we aren't depending on the global state in our tests.
This also updates a couple locations that change exceptions
backtraces to avoid them pointing to the internals of ardb. They
previously used `tap` to one-line …

Raise not initialized error when using `adapter` before `init`

---

ardb.gemspec
lib/ardb.rb
lib/ardb/adapter/base.rb
lib/ardb/adapter/postgresql.rb
test/unit/adapter/postgresql_tests.rb
test/unit/ardb_tests.rb

This validation isn't appropriate for all db engines. Specifically
Sqlite uses db names such as `path/to/mydb.sqlite` or `:memory:`.
This validation is really only needed for Postgres as far as I've
seen.
Thanks to @jcredding for noticing this in a real-world use case.

move configured db name validation to Postgres adapter

---

README.md
lib/ardb/cli/commands.rb
test/unit/cli_tests.rb

This adds some description and usage information. This really just
covers configuration and the CLI. I chose to not highlight some of
the other testing related tools as I think they need to be updated
for Rails 5. Others are tied to using Assert and are esoteric.
As I address the other tools, I'll add README descriptions for
them later on.
The README includes a bunch of CLI output to give an impression
of what working with the CLI is like and what tools it offers.
While preparing the README, I noticed some inconsistencies with
the output on success vs error on certain commands. This cleans
up the output to always use inspect instead of back-ticks.
I also noticed that the help output for `generate-migration`
didn't describe the MIGRATION-NAME parameter. This was an error
from previously …

add a first-pass README

---

README.md
lib/ardb.rb
test/unit/ardb_tests.rb

This updates the `Ardb::Config` to allow setting a
`default_timezone` which is then used to set
`ActiveRecord::Base.default_timezone`. This allows setting this
with the rest of the ActiveRecord configuration and avoids having
to manually set it separately.

Allow configuring `ActiveRecord::Base.default_timezone`

---

Gemfile
ardb.gemspec
lib/ardb/require_autoloaded_active_record_files.rb
script/determine_autoloaded_active_record_files.rb
test/unit/adapter/base_tests.rb

This updates the `require_autoloaded_active_record_files` script
to support ActiveRecord 6.1. This was previously updated to
support ActiveRecord 6.0 but some files have been removed and
added in ActiveRecord 6.1 and the previous didn't work for it.
This also fixes an error that would occur when
`ActiveRecord::MigrationContext` wasn't required before running
the `Adapter::Base` tests. This requires `active_record/migration`
to ensure it's always available.
Finally, this updates to support ruby 2.5 and greater going
forward to match other gems.

Update "require autoloaded" script to support ActiveRecord 6.1
